# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b53819fdb395771cb5dedfc03d13aec5966d62329e1814e99872a057d6e64215a2a0f091690f680f3e09d9801c04d503008670be5790a95fb282736d30a1019

test:
  secret_key_base: 63c8f315e7329c40792f46ae807fedcbe4bb8a448f7a80561f66611c0b3dd31d92f142761e85016c3862346f4fa791769547dc68efaced7179ed43fe8ce77ea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
